matrix:
  include:
    - language: node_js
      node_js: 14
      before_install:
        - cd frontend
        - npm install -g yarn
      install:
        - yarn install
      script:
        - yarn test
        - yarn lint
        - yarn build

    - language: php
      php: 7.4
      cache:
        directories:
          - $HOME/.composer/cache/files
      before_script:
        - cd api
        - composer install
      script:
        - composer run-script travis
      after_success:
        - travis_retry php vendor/bin/php-coveralls
