matrix:
  include:
    - language: node_js
      node_js: 13
      install:
        - cd frontend
        - yarn install
      script:
        - yarn test
        - yarn lint
        - yarn build

    - language: php
      php: 7.4
      before_script:
        - cd api
        - composer install
      script:
        - vendor/bin/phpunit -c phpunit.xml --coverage-clover clover.xml
        - vendor/bin/phpcs -q -n --colors --standard=ruleset.xml --runtime-set ignore_warnings_on_exit true
      after_script:
        - php vendor/bin/php-coveralls --coverage_clover=clover.xml -v
