version: "3.6"

services:
  joekozak-php:
    image: elliotjreed/joekozak-php
    container_name: joekozak-php
    restart: always
    networks:
      - joekozak
    volumes:
      - ./.env:/var/www/html/.env

  joekozak-api-nginx:
    image: elliotjreed/joekozak-api-nginx
    container_name: joekozak-api-nginx
    restart: always
    networks:
      - joekozak
      - web
    depends_on:
      - joekozak-php
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:api.joekozak.co.uk"
      - "traefik.protocol=h2c"
      - "traefik.port=91"

  joekozak-nginx:
    image: elliotjreed/joekozak-nginx
    container_name: joekozak-nginx
    restart: always
    networks:
      - joekozak
      - web
    depends_on:
      - joekozak-php
      - joekozak-api-nginx
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:joekozak.co.uk"
      - "traefik.www.frontend.rule=Host:www.joekozak.co.uk"
      - "traefik.protocol=h2c"
      - "traefik.port=90"

networks:
  web:
    external: true
  joekozak:
    name: joekozak

